# -*- coding: utf-8 -*-
"""
Created on Wed Feb  1 22:29:03 2023

@author: sabyasachi
"""

# Random State
random_state: 42

# Dataset Path
dataset:
  # Training Dataset Path
  training_data_path: './datasets/symtoms_train.csv'
  # Test Dataset Path
  test_data_path: './datasets/symtoms_test.csv'
  # Validation Data Size for train_test_split
  validation_size: 0.20

# Model Parameters
model:
  # Decision Tree
  decision_tree:
    criterion: 'entropy'

  # Random Forest Classifier
  random_f:
    n_estimators: 50

# Model Save Path
model_save_path: './saved_model/'